def label = "maven-${UUID.randomUUID().toString()}"

podTemplate(label: label, containers: [
  containerTemplate(name: 'maven-build', image: 'maven:3.3.9-jdk-8-alpine', ttyEnabled: true, command: 'cat')
  ]) {

  node(label) {
    stage('Checkout') {
      git 'https://github.com/GaryLouisStewart/jenkins-demos.git'
      parallel (
        build: {
          container('maven-build') {
            stage('Build Maven App') {
              sh 'cd mvn-app/ && mvn -B clean package'
            }
          }
        },
        test: {
          container('maven-build') {
            stage('Test Maven app') {
              steps {
               sh 'cd mvn-app/ && mvn test'
              }
              post {
                always {
                  junit 'target/surefire-reports/*.xml'
                }
              }
            stage('Deliver') {
              steps {
                sh './jenkins/scripts/deliver.sh'
              }
            }   
          }
        )
      }
    }
  }
}
