def label = "maven-${UUID.randomUUID().toString()}"

podTemplate(label: label, containers: [
  containerTemplate(name: 'maven', image: 'maven:3.3.9-jdk-8-alpine', ttyEnabled: true, command: 'cat')
  ]) {

  node(label) {
    stage('Build a Maven project') {
      git 'https://github.com/GaryLouisStewart/jenkins-demos.git'
      container('maven') {
          sh 'cd mvn-app/'
          sh 'mvn -B clean package'
      }
    }
  }
}