pipeline {
  agent {
    kubernetes {
      label 'python-example-1'
      yamlFile 'python-app/declarative-pipeline/pythonContainer.yaml'
    }
  }
  stages {
    stage('build') {
      steps {
        sh "echo Build Django Polls Application.........."
        container('python') {
          sh """
          cd python-app/polls_site
          python manage.py migrate
          python manage.py makemigrations polls
          python manage.py sqlmigrate polls 0001
          """
        }
      }
    }
    stage('Test Django Polls Models') {
      steps {
        sh "echo Running tests.........."
        container('python') {
          sh 'cd python-app/polls_site && python manage.py test polls -v 2'
        }
      }
    }
  }
}